<!doctype html>
<html lang="es-MX">
<?php include(VIEWS_DIR . "/partials/head.phtml"); ?>
<body>
<?php include(VIEWS_DIR . "/partials/header.phtml"); ?>
<main class="container">
    <h1>Registro</h1>
    <form action="/add-user-success" method="POST" enctype="multipart/form-data">
        <div class="form-group">
            <label for="name">Nombre</label>
            <input type="text" required
                   class="form-control"
                   id="name"
                   name="name"
                   placeholder="Ingresa tu nombre" />
        </div>
        <div class="form-group">
            <label for="address">Domicilio</label>
            <input type="text"
                   class="form-control"
                   id="address"
                   name="address"
                   placeholder="Ingresa tu domicilio" />
        </div>
        <div class="form-group">
            <label for="email">E-mail</label>
            <input type="text"
                   class="form-control"
                   id="email"
                   name="email"
                   placeholder="Ingresa tu e-mail" />
        </div>
        <div class="form-group">
            <label for="pass">Password</label>
            <input type="text"
                   class="form-control"
                   id="pass"
                   name="pass"
                   placeholder="Ingresa tu password" />
        </div>
        <button type="submit" class="btn btn-primary">Registrar</button>
    </form>
</main>
<?php include(VIEWS_DIR . "/partials/footer.phtml"); ?>
<?php include(VIEWS_DIR . "/partials/scripts.phtml"); ?>
</body>
</html>
